export const defaultContent = {
  profile: {
    name: 'Bobby Domdom Jr',
    firstName: 'Bobby',
    role: 'Database Administrator · IT Operations · Web Development',
    location: 'Manila, Philippines',
    email: 'bobby.domdomjr1@gmail.com',
    phone: '+639511033187',
    website: 'https://e-portfolio-ochre-sigma.vercel.app/',
    image: '/assets/img/profile.jpeg',
    availability: 'Open to the right technology opportunity',
    social: {
      linkedin: 'https://www.linkedin.com/in/bobbydomdomjr',
      github: '',
      instagram: 'https://www.instagram.com/bobby.domdomjr',
      facebook: 'https://www.facebook.com/bobby.domdomjr',
    },
  },
  about: 'I help teams keep technology dependable and make digital experiences easier to use. My background spans database administration, IT operations, end-user support, and web development—with a practical focus on security, reliability, and clear communication.',
  headline: 'Reliable systems. Thoughtful digital experiences.',
  experience: [
    {
      title: 'Database Administrator',
      organization: 'Headquarters Philippine Navy — Naval Systems Engineering, N11',
      period: '2025 — Present',
      description: 'Database design and implementation, performance tuning, data security, backups, and troubleshooting.',
    },
    {
      title: 'IT Specialist I',
      organization: 'STI College Naga, Camarines Sur',
      period: '2023 — 2025',
      description: 'Supported staff and students, maintained computer laboratories, managed user accounts, and helped strengthen data security.',
    },
    {
      title: 'DICT Intern',
      organization: 'Department of Information and Communications Technology · Legazpi City',
      period: '2022 — 2023',
      description: 'Contributed to design and marketing materials, presentations, and creative project work.',
    },
  ],
  education: [
    {
      title: 'Bachelor of Science in Information Systems',
      organization: 'Bicol University — Polangui',
      period: '2019 — 2023',
      description: 'Studies spanning information technology, business processes, and organizational information systems.',
    },
    {
      title: 'Civil Service Eligibility & Fire Officer Eligibility',
      organization: 'Civil Service Commission · Fire Officer Examination',
      period: '2023 · 2024',
      description: 'Double eligibility.',
    },
  ],
  skills: [
    { name: 'Database administration', level: 88 },
    { name: 'HTML & CSS', level: 92 },
    { name: 'JavaScript & TypeScript', level: 84 },
    { name: 'PHP & MySQL', level: 84 },
    { name: 'IT support & security', level: 90 },
    { name: 'UI/UX design', level: 80 },
    { name: 'Python', level: 78 },
    { name: 'WordPress & CMS', level: 84 },
  ],
  testimonials: [],
  projects: [
    {
      id: 'nexus-mobile',
      title: 'Nexus mobile app concept',
      category: 'App',
      year: '2024',
      image: '/assets/img/portfolio/nexus-1.png',
      description: 'A mobile app concept focused on simple navigation, accessible interface patterns, and a cohesive visual system.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['UI/UX', 'Mobile design', 'Prototype'],
      link: '',
    },
    {
      id: 'nexus-web',
      title: 'Nexus web experience',
      category: 'Web',
      year: '2024',
      image: '/assets/img/portfolio/nexus-2.png',
      description: 'Responsive web interface exploration with clear content structure and consistent visual components.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Web design', 'Responsive', 'UI/UX'],
      link: '',
    },
    {
      id: 'dashboard',
      title: 'Dashboard interface',
      category: 'Web',
      year: '2023',
      image: '/assets/img/portfolio/1.png',
      description: 'Dashboard concept with information-rich views, useful summaries, and clear navigation.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Dashboard', 'UI design', 'Data'],
      link: '',
    },
    {
      id: 'design-app',
      title: 'Mobile app screens',
      category: 'App',
      year: '2023',
      image: '/assets/img/portfolio/portfolio-3.jpg',
      description: 'An app screen design study exploring clear task flows and a consistent component system.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['App design', 'Interface'],
      link: '',
    },
    {
      id: 'brand-cards',
      title: 'Digital card design',
      category: 'Design',
      year: '2022',
      image: '/assets/img/portfolio/portfolio-4.jpg',
      description: 'A collection of visual design concepts for digital and print applications.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Graphic design', 'Visual identity'],
      link: '',
    },
    {
      id: 'site-refresh',
      title: 'Website refresh',
      category: 'Web',
      year: '2024',
      image: '/assets/img/portfolio/portfolio-5.jpg',
      description: 'A web design exploration centered around clear information architecture and reusable page sections.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Web design', 'Content'],
      link: '',
    },
    {
      id: 'utility-app',
      title: 'Utility app interface',
      category: 'App',
      year: '2023',
      image: '/assets/img/portfolio/portfolio-6.jpg',
      description: 'An interface concept for everyday tasks with a focus on legibility and ease of use.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['App design', 'Interface'],
      link: '',
    },
    {
      id: 'print-design',
      title: 'Invitation & stationery',
      category: 'Design',
      year: '2022',
      image: '/assets/img/portfolio/portfolio-7.jpg',
      description: 'Coordinated invitation and stationery design with considered typography and layout.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Print', 'Graphic design'],
      link: '',
    },
    {
      id: 'landing-page',
      title: 'Landing page concept',
      category: 'Web',
      year: '2023',
      image: '/assets/img/portfolio/portfolio-9.jpg',
      description: 'A modular landing page layout for presenting information with a clear visual hierarchy.',
      caseStudy: { challenge: '', approach: '', outcome: '' },
      tags: ['Web design', 'Landing page'],
      link: '',
    },
  ],
  services: [
    {
      title: 'Web development',
      description: 'Responsive, maintainable websites built around real user needs.',
      icon: '01',
    },
    {
      title: 'UI/UX design',
      description: 'Practical screen layouts, interfaces, and accessible user journeys.',
      icon: '02',
    },
    {
      title: 'IT support',
      description: 'Hardware, software, user accounts, and everyday technical troubleshooting.',
      icon: '03',
    },
    {
      title: 'Database administration',
      description: 'Database design, performance, backups, and dependable data practices.',
      icon: '04',
    },
    {
      title: 'WordPress & CMS',
      description: 'Content-managed sites that are easy to update and maintain.',
      icon: '05',
    },
    {
      title: 'Creative projects',
      description: 'Photography, visual design, and thoughtful digital experiences.',
      icon: '06',
    },
  ],
}
